### ISSUE TITLE
add some more Diwali Wishes in db.json file

### ISSUE THREAD

**Issue by iamsonukushwaha** [iamsonukushwaha/JSON#1]
- add more Diwali Wishes in  [db.json](https://github.com/flyingsonu122/JSON/blob/master/db.json) file
- it can be in any language.

- please do not repeat the same Wish again

- submit your pull request

Happy Diwali 🎉

**Comment by Poobalan1210** [comment]
I would like to work on this issue once hacktoberfest starts

**Comment by jhalak27** [comment]
Hey, I am new here. Can I work on this?

**Comment by flyingsonu122** [comment]
@jhalak27 yes, go ahead

**Comment by AkshatRastogi-1nC0re** [comment]
Hey I would like to work on this issue.

**Comment by flyingsonu122** [comment]
> Hey I would like to work on this issue.

Yeah sure, go ahead

**Comment by AkshatRastogi-1nC0re** [comment]
> > Hey I would like to work on this issue.
> 
> Yeah sure, go ahead

I have added some wishes, but I cant push the changes. How do I do that?

**Comment by flyingsonu122** [comment]
> > > Hey I would like to work on this issue.
> > 
> > 
> > Yeah sure, go ahead
> 
> I have added some wishes, but I can't push the changes. How do I do that?

Done, Thanks for contributing!

**Comment by Dvd1234** [comment]
Hey @flyingsonu122 Submitted a PR- https://github.com/flyingsonu122/JSON/pull/46
Please do the needful.

Many Thanks.
